### PR TITLE
Start adding banner.

### PR DESCRIPTION
**Pull request by andyvh**
A first shot at adding the banner to the front page. Really just a placeholder until I work out how to test the view on my machine.

### CODE REVIEW

**Comment by EvanGee** [comment]
I added build instructions, for the development server it should reload if you make any changes!

**Comment by andyvh** [comment]
I notice that this is still open, despite their being a solution on the original issue; should I wrap it up myself, or have you taken the other solution as final?

**Comment by Spensaur-K** [comment]
@andyvh I think you are the only one who has started working on a banner.

**Comment by Spensaur-K** [comment]
@andyvh Yes, sorry it seems that somebody else beat you to it.

**Comment by andyvh** [comment]
No worries, I'd thought so!

**Pull request closed without merging**
